
if (WIN32 AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${NAME_STD}.wc)
	set (TEXE_ICON ${PROJECT_SOURCE_DIR}/../${NAME_STD}.ico)
	configure_file(${CMAKE_CURRENT_SOURCE_DIR}/${NAME_STD}.wc ${CMAKE_CURRENT_BINARY_DIR}/${NAME_STD}.rc)
	set (MAINSRCS ${MAINSRCS} ${CMAKE_CURRENT_BINARY_DIR}/${NAME_STD}.rc)
endif()

add_executable(${NAME_STD} ${MAINSRCS})
set_target_properties(${NAME_STD} PROPERTIES
	VERSION ${TEXE_VERSION}
	SOVERSION ${TEXE_VERSION}
	INSTALL_RPATH_USE_LINK_PATH TRUE
	LINK_FLAGS ${COMMON_LINKER_FLAGS}
	COMPILE_FLAGS ${COMMON_CXX_FLAGS}
)
target_link_libraries(${NAME_STD} ${EXECLIBS})
install (TARGETS ${NAME_STD} RUNTIME DESTINATION bin)
