
if (WIN32 AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${NAME_STD}.wc)
	set (TEXE_ICON ${PROJECT_SOURCE_DIR}/../${NAME_STD}.ico)
	configure_file(${CMAKE_CURRENT_SOURCE_DIR}/${NAME_STD}.wc ${CMAKE_CURRENT_BINARY_DIR}/${NAME_STD}.rc)
	set (MAINSRCS ${MAINSRCS} ${CMAKE_CURRENT_BINARY_DIR}/${NAME_STD}.rc)
	set (EXECLIBS ${EXECLIBS} wsock32)
endif()

if (WIN32)
	set (MAINSRCS ${MAINSRCS} ${PROJECT_SOURCE_DIR}/src/getopt.c ${PROJECT_SOURCE_DIR}/src/getopt-repl.h)
endif()

add_executable(${NAME_STD} ${MAINSRCS})
set_target_properties(${NAME_STD} PROPERTIES
	INSTALL_RPATH_USE_LINK_PATH TRUE
	LINK_FLAGS ${COMMON_LINKER_FLAGS}
	COMPILE_FLAGS ${COMMON_CXX_FLAGS}
)
target_link_libraries(${NAME_STD} ${EXECLIBS} ${COMMONLIBS})
install (TARGETS ${NAME_STD} RUNTIME DESTINATION bin)
