add_library(${TLIB_NAME} STATIC ${TLIB_SRCS})
set_target_properties(${TLIB_NAME} PROPERTIES
	VERSION ${TLIB_VERSION}
	SOVERSION ${TLIB_VERSION}
	LINK_FLAGS ${COMMON_LINKER_FLAGS}
	COMPILE_FLAGS ${COMMON_CXX_FLAGS}
)
target_link_libraries(${TLIB_NAME} ${TLIB_DEPLIBS})

install (TARGETS ${TLIB_NAME} 
 RUNTIME DESTINATION bin
 LIBRARY DESTINATION lib
 ARCHIVE DESTINATION lib/static)