add_library(${TLIB_NAME} SHARED ${TLIB_SRCS})
set_target_properties(${TLIB_NAME} PROPERTIES
	VERSION ${TLIB_VERSION}
	SOVERSION ${TLIB_VERSION}
	LINK_FLAGS ${COMMON_LINKER_FLAGS}
	COMPILE_FLAGS ${COMMON_CXX_FLAGS}
)
install (TARGETS ${TLIB_NAME} LIBRARY DESTINATION lib)