option(QF_WITH_NEW_ALLOCATOR "Compile with the new allocator" OFF)
option(QF_WITH_CALLSTACK "display c++ call stack after crashing" OFF)
option(QF_WITH_BOOST "Use boost library" OFF)
option(QF_WITH_MYSQL "Enable mysql support" OFF)
option(QF_WITH_POSTGRESQL "Enable Postgresql support" OFF)
option(QF_WITH_PYTHON "Enable Python support" OFF)
option(QF_WITH_JAVA "Enable Java support" OFF)
option(QF_WITH_RUBY "Enable Ruby support" OFF)
option(QF_WITH_EXAMPLES "Build Quickfix Examples (note: headers must be installed for these to work)" OFF)
